### ISSUE TITLE
Notify on Reconnects

### ISSUE THREAD

**Issue by alexanderkiel** [billstclair/elm-websocket-client#4]
Hi, I have a web socket with a pub/sub protocol, were the client subscribes to topics. If you reconnect because of a short time connection failure, I need to know this, because I have to resubscribe to my topics. Otherwise I have a new connection to the server but my subscriptions are lost. The protocol is described [here][1].

[1]: <https://github.com/alexanderkiel/samply.broker.search.store/blob/event-stream/doc/event-stream-protocol.md>

**Comment by billstclair** [comment]
I recommend disabling automatic reconnection, and doing the reconnect and resubscribe yourself, in response to a `ClosedResponse`.

https://package.elm-lang.org/packages/billstclair/elm-websocket-client/latest/PortFunnel-WebSocket#setAutoReopen

This is only available in version 3.x, though, so if you're on 2.x, you'll need to upgrade, or, if you don't want to upgrade, you'll need to add the source to your project, and patch it to disable auto-reopen.

**Comment by alexanderkiel** [comment]
Thanks. I chose to go with Version 2.x because I found the PortFunnel version to complex and the documentation not up to date. I'll try again.

**Comment by billstclair** [comment]
Understood. My first `PortFunnel` version was hard to understand. I hope that the addition of the `PortFunnels.elm` file, which you can use unchanged if you only use this one module, makes that easier. Let me know.

And if the docs are still not up to date, please make an issue, so I'll know what to fix.

**Comment by alexanderkiel** [comment]
I thought a bit more about this issue. You suggested to use [setAutoReopen][1]. But if I do this, I will have to reimplement your reconnection logic. It would be much better to simply get a notification wether a connection was reestablished. So maybe just a parameter to the `ConnectedResponse`?  

[1]: <https://package.elm-lang.org/packages/billstclair/elm-websocket-client/latest/PortFunnel-WebSocket#setAutoReopen>

**Comment by billstclair** [comment]
Good idea. I'll do it soon.

**Comment by billstclair** [comment]
Fixed by 400583f

See https://package.elm-lang.org/packages/billstclair/elm-websocket-client/4.0.0/PortFunnel-WebSocket#Response

I added a `ReconnectedResponse`, and, since it can be returned in a `ListResponse`, I documented that and added [`reconnectedResponses`](https://package.elm-lang.org/packages/billstclair/elm-websocket-client/4.0.0/PortFunnel-WebSocket#reconnectedResponses) to help filter the `ListResponse`.

The addition of the new `Response` tag caused a major version bump.
