### ISSUE TITLE
What's needed on the JavaScript side to get the proper state inside the "scope" variable?

### ISSUE THREAD

**Issue by ReuvenSwirsky** [billstclair/elm-websocket-client#9]
I have this working (thanks!) but I had to do a little hack to get the PortFunnel module visible to the WebSocket module. (I realize this isn't really your issue, but it may help other Elm people who are coming to Elm without a grounding in JavaScript conventions for modules and scoping.)

```
// ....
var app = Elm[mainModule].init({
    node: document.getElementById('elm-app'), 
    flags: {},
  });

window.PortFunnel = PortFunnel;    // <----- HACK

PortFunnel.subscribe(app);
// ....
```

and then in WebSocket I had to

```
(function(scope) {
    var moduleName = 'WebSocket';
  
    var sub;
  
    function init() {
      // was "scope.Portfunnel" *** ***
      var PortFunnel = window.PortFunnel;

      if (!PortFunnel || !PortFunnel.sub || !PortFunnel.modules) {
        // Loop until PortFunnel.js has initialized itself.
        setTimeout(init, 10);
        return;
      }

```
My question is -- what protocol do I need to follow to get "PortFunnel" visible in that "scope" variable that's passed to the module init? I'm using webpack to process all the JavaScript for my Elm project, and I don't have a lot of experience in this area. I presume you were using some other JavaScript scoping and initialization scheme that's not compatible with the WebPack one. 

What _should_ I be doing?

**Comment by billstclair** [comment]
I don't know. I've never used WebPack. I suppose I'll have to learn it, and change the code to do the right thing, but since you've solved your problem for now, I'm in no hurry to do that.

**Comment by ReuvenSwirsky** [comment]
Thanks! I'll try to figure this out and I'll let you know what I did. The latest "state of the art" for people doing Elixir/Erlang + Elm is to use WebPack. 

This may not be a webpack thing at all. It could just be my failure to understand how ES6 imports/exports work!
